name: CRAFT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0' # The R version to download (if necessary) and use.
    
    - run: Rscript -e 'print("hello")'
    - run: R -e 'install.packages(https://bioconductor.org/packages/release/bioc/bin/macosx/big-sur-arm64/contrib/4.3/RcisTarget_1.22.0.tgz, repos = NULL, type="source")'
           R -e 'install.packages(https://cran.r-project.org/src/contrib/tibble_3.2.1.tar.gz, repos = NULL, type="source")'

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    # - name: Install boost
    #   run: |
    #       conda install -c conda-forge boost
    #       conda install -c conda-forge eigen
    #   shell: bash
    - name: Installing and setting up dependencies
      run: |
        export CPATH=$CPATH:/usr/local/include
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        bash test_setup.sh
    
    - name: Test with pytest
      run: |
        python -m pytest tests/unittest
    
