name: CRAFT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Setup cytoscape
      run: |
        curl https://github.com/cytoscape/cytoscape/releases/download/3.9.1/Cytoscape_3_9_1_unix.sh -o Cytoscape_3_9_1_unix.sh
        chmod u+x  Cytoscape_3_9_1_unix.sh
        sh Cytoscape_3_9_1_unix.sh 
        Cytoscape &
    # - name: Set up Python 3.9
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.9"
    # - name: Installing and setting up dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    #     bash setup.sh
    # - name: Installing R
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    #     bash setup.sh
    # - name: Test with pytest
    #   run: |
    #     pytest
    # - name: Setup Python
    #   uses: actions/setup-python@v5.0.0